[sources.facebook_ads]
access_token = "ADD HERE"

[destination.bigquery]
location = "ADD HERE"
[destination.bigquery.credentials]
project_id = "ADD HERE"
private_key = "ADD HERE"
client_email = "ADD HERE"
