models:
  - name: mrt_shopify__orders
    columns:
      - name: order_id
        data_type: int64
        data_tests:
          - not_null
          - unique
        quote: true
      - name: customer_id
        data_type: int64
        data_tests:
          - not_null
        quote: true
      - name: total_discounts
        data_type: float64
        quote: true
      - name: total_line_items_price
        data_type: float64
        quote: true
      - name: total_price
        data_type: float64
        quote: true
      - name: total_shipping_price
        data_type: float64
        quote: true
      - name: total_subtotal_price
        data_type: float64
        quote: true
      - name: total_tax
        data_type: float64
        quote: true
      - name: taxes_included
        data_type: boolean
        quote: true
      - name: created_at
        data_type: timestamp
        quote: true
      - name: cancelled_at
        data_type: timestamp
        quote: true
      - name: closed_at
        data_type: timestamp
        quote: true
      - name: processed_at
        data_type: timestamp
        quote: true
      - name: updated_at
        data_type: timestamp
        quote: true
      - name: discount_code_code
        data_type: string
        quote: true
      - name: shipping_discount
        data_type: float64
        quote: true
      - name: line_item_discount
        data_type: float64
        quote: true
      - name: refund_transactions_id
        data_type: string
        quote: true
      - name: refund_transactions_amount
        data_type: float64
        quote: true
      - name: refund_transactions_created_at
        data_type: timestamp
        quote: true
      - name: refund_transaction_kind
        data_type: string
        quote: true
      - name: refund_transactions_status
        data_type: string
        quote: true
      - name: net_revenue
        data_type: float64
        quote: true
      - name: nth_order
        data_type: int64
        quote: true
      - name: new_customer
        data_type: int64
        quote: true
  - name: mrt_shopify__revenue_by_day
    columns:
      - name: created_at_date
        data_type: date
        data_tests:
          - not_null
          - unique
        quote: true
      - name: existing_customer_net_revenue
        data_type: float64
        data_tests:
          - not_null
        quote: true
      - name: new_customer_net_revenue
        data_type: float64
        data_tests:
          - not_null
        quote: true
      - name: net_revenue
        data_type: float64
        data_tests:
          - not_null
        quote: true
