WITH shopify AS (
    SELECT * FROM opensource-marketing-dwh.shopify.shopify_orders
),

-- removes columns that are not needed at the moment
filter_source AS (
    SELECT
        id AS order_id,
        customer_id,
        -- app_id,
        -- cancel_reason,
        -- totals
        total_discounts,
        total_line_items_price,
        total_price,
        -- total_price_usd,
        total_shipping_price,
        total_subtotal_price,
        total_tax,
        -- total_tip_received,

        -- cart_token,
        -- checkout_id,
        -- checkout_token,
        -- timestamps
        created_at,
        cancelled_at,
        closed_at,
        processed_at,
        updated_at,
        -- client details
        -- client_details_accept_language,
        -- client_details_browser_height,
        -- client_details_browser_ip,
        -- client_details_browser_width,
        -- client_details_session_hash,
        -- client_details_user_agent,
        -- confirmed,
        -- currency,
        -- customer_accepts_marketing,
        -- customer_accepts_marketing_updated_at,
        -- customer_created_at,
        -- customer_uid,
        -- customer_locale,
        -- customer_multipass_identifier,
        -- customer_note,
        -- customer_state,
        -- customer_tags,
        -- customer_tax_exempt,
        -- customer_total_spent,
        -- customer_updated_at,
        -- device_id,
        -- discount application
        discount_application_allocation_method,
        discount_application_code,
        discount_application_target_selection,
        discount_application_target_type,
        discount_application_type,
        discount_application_value,
        discount_application_value_type,
        discount_application_title,
        discount_application_description,
        discount_code_amount,
        discount_code_code,
        discount_code_type,
        -- financial_status,
        -- fulfillment_status,
        -- gateway,
        -- uid,
        landing_site,
        -- landing_site_ref,
        -- fulfillments_location_id,
        -- fulfillments_line_item_id,
        -- line items
        -- line_item_discount_allocations_amount,
        -- line_item_discount_allocations_application_index,
        -- line_item_fulfillable_quantity,
        -- line_item_fulfillment_service,
        -- line_item_fulfillment_status,
        -- line_item_gift_card,
        -- line_item_grams,
        -- line_item_id,
        -- line_item_uid,
        -- line_item_name,
        -- line_item_price,
        -- line_item_product_exists,
        -- line_item_product_id,
        -- line_item_product_uid,
        -- line_item_properties,
        -- line_item_quantity,
        -- line_item_requires_shipping,
        -- line_item_sku,
        -- line_item_tax_lines_price,
        -- line_item_tax_lines_rate,
        -- line_item_tax_lines_title,
        -- line_item_taxable,
        -- line_item_title,
        -- line_item_variant_id,
        -- line_item_variant_uid,
        -- line_item_vendor,
        -- line_item_variant_inventory_management,
        -- line_item_variant_title,
        -- location_id,
        -- name,
        -- note,
        -- number,
        -- order adjustment
        order_adjustment_amount,
        order_adjustment_id,
        order_adjustment_uid,
        order_adjustment_kind,
        order_adjustment_reason,
        order_adjustment_refund_id,
        order_adjustment_refund_uid,
        order_adjustment_tax_amount,
        -- order_number,
        -- order_status_url,
        -- payment_details_avs_result_code,
        -- payment_details_credit_card_company,
        payment_gateway_names,
        presentment_currency,
        -- processing_method,
        -- reference,
        referring_site,
        -- refunds
        refund_line_item_created_at,
        refund_line_item_order_line_item_id,
        refund_line_item_processed_at,
        refund_line_item_quantity,
        refund_line_item_refund_id,
        refund_line_item_refund_line_item_id,
        refund_line_item_restock,
        refund_line_item_restock_type,
        refund_transactions_id,
        refund_transactions_amount,
        refund_transactions_created_at,
        refund_transactions_kind,
        refund_transactions_status,
        -- shipping address
        -- shipping_address_city,
        -- shipping_address_country,
        -- shipping_address_country_code,
        -- shipping_address_province,
        -- shipping_address_province_code,
        -- shipping_address_zip,
        -- shipping_line_code,
        -- billing_address_city,
        -- billing_address_zip,
        billing_address_country_code, -- billing address is relevant to see where the money goes to
        -- shipping
        shipping_line_discount_allocations_index,
        shipping_line_discount_amount,
        shipping_line_discounted_price,
        shipping_line_id,
        shipping_line_uid,
        shipping_line_price,
        shipping_line_source,
        shipping_line_tax_lines_price,
        shipping_line_tax_lines_rate,
        shipping_line_tax_lines_title,
        shipping_line_title,

        -- source_identifier,
        -- source_name,
        -- source_url,
        -- tags,

        -- tax
        tax_line_price,
        tax_line_rate,
        tax_line_title,
        taxes_included,
        test,
        -- token,
        -- total_weight,
        -- user_id,
        -- record_timestamp
    FROM shopify
    -- we want to remove test orders
    WHERE test IS false
)

SELECT * FROM filter_source
