models:
  - name: mrt_facebook_ads
    description: "Grain: one row per ad(_id) per day"
    columns:
      - name: account_id
        data_type: string
        quote: true
      - name: campaign_id
        data_type: int64
        quote: true
      - name: adset_id
        data_type: int64
        quote: true
      - name: ad_id
        data_type: int64
        data_tests:
          - not_null
        quote: true
      - name: insight_date
        data_type: date
        quote: true
      - name: reach
        data_type: int64
        quote: true
      - name: impressions
        data_type: int64
        quote: true
      - name: frequency
        data_type: numeric
        quote: true
      - name: clicks
        data_type: int64
        quote: true
      - name: unique_clicks
        data_type: int64
        quote: true
      - name: ctr
        data_type: numeric
        quote: true
      - name: unique_ctr
        data_type: numeric
        quote: true
      - name: cpc
        data_type: numeric
        quote: true
      - name: cpm
        data_type: numeric
        quote: true
      - name: cpp
        data_type: numeric
        quote: true
      - name: spend
        data_type: numeric
        quote: true
      - name: _dlt_load_id
        data_type: string
        quote: true
      - name: _dlt_id
        data_type: string
        quote: true
      - name: offsite_fb_pixel_add_to_cart_value
        data_type: float64
        quote: true
      - name: offsite_fb_pixel_purchase_value
        data_type: float64
        quote: true
      - name: offsite_fb_pixel_add_to_cart
        data_type: float64
        quote: true
      - name: offsite_fb_pixel_purchase
        data_type: float64
        quote: true
      - name: ad_name
        data_type: string
        quote: true
      - name: campaign_name
        data_type: string
        quote: true
