models:
  - name: int_shopify__orders
    columns:
      - name: order_id
        data_type: int64
        quote: true
      - name: customer_id
        data_type: int64
        quote: true
      - name: total_discounts
        data_type: float64
        quote: true
      - name: total_line_items_price
        data_type: float64
        quote: true
      - name: total_price
        data_type: float64
        quote: true
      - name: total_shipping_price
        data_type: float64
        quote: true
      - name: total_subtotal_price
        data_type: float64
        quote: true
      - name: total_tax
        data_type: float64
        quote: true
      - name: created_at
        data_type: timestamp
        quote: true
      - name: cancelled_at
        data_type: timestamp
        quote: true
      - name: closed_at
        data_type: timestamp
        quote: true
      - name: processed_at
        data_type: timestamp
        quote: true
      - name: updated_at
        data_type: timestamp
        quote: true
      - name: discount_application_allocation_method
        data_type: string
        quote: true
      - name: discount_application_code
        data_type: string
        quote: true
      - name: discount_application_target_selection
        data_type: string
        quote: true
      - name: discount_application_target_type
        data_type: string
        quote: true
      - name: discount_application_type
        data_type: string
        quote: true
      - name: discount_application_value
        data_type: string
        quote: true
      - name: discount_application_value_type
        data_type: string
        quote: true
      - name: discount_application_title
        data_type: string
        quote: true
      - name: discount_application_description
        data_type: string
        quote: true
      - name: discount_code_amount
        data_type: string
        quote: true
      - name: discount_code_code
        data_type: string
        quote: true
      - name: discount_code_type
        data_type: string
        quote: true
      - name: landing_site
        data_type: string
        quote: true
      - name: order_adjustment_amount
        data_type: string
        quote: true
      - name: order_adjustment_id
        data_type: string
        quote: true
      - name: order_adjustment_uid
        data_type: string
        quote: true
      - name: order_adjustment_kind
        data_type: string
        quote: true
      - name: order_adjustment_reason
        data_type: string
        quote: true
      - name: order_adjustment_refund_id
        data_type: string
        quote: true
      - name: order_adjustment_refund_uid
        data_type: string
        quote: true
      - name: order_adjustment_tax_amount
        data_type: string
        quote: true
      - name: payment_gateway_names
        data_type: string
        quote: true
      - name: presentment_currency
        data_type: string
        quote: true
      - name: referring_site
        data_type: string
        quote: true
      - name: refund_line_item_created_at
        data_type: string
        quote: true
      - name: refund_line_item_order_line_item_id
        data_type: string
        quote: true
      - name: refund_line_item_processed_at
        data_type: string
        quote: true
      - name: refund_line_item_quantity
        data_type: string
        quote: true
      - name: refund_line_item_refund_id
        data_type: string
        quote: true
      - name: refund_line_item_refund_line_item_id
        data_type: string
        quote: true
      - name: refund_line_item_restock
        data_type: string
        quote: true
      - name: refund_line_item_restock_type
        data_type: string
        quote: true
      - name: refund_transactions_id
        data_type: string
        quote: true
      - name: refund_transactions_amount
        data_type: string
        quote: true
      - name: refund_transactions_created_at
        data_type: string
        quote: true
      - name: refund_transactions_kind
        data_type: string
        quote: true
      - name: refund_transactions_status
        data_type: string
        quote: true
      - name: billing_address_country_code
        data_type: string
        quote: true
      - name: shipping_line_discount_allocations_index
        data_type: string
        quote: true
      - name: shipping_line_discount_amount
        data_type: string
        quote: true
      - name: shipping_line_discounted_price
        data_type: string
        quote: true
      - name: shipping_line_id
        data_type: string
        quote: true
      - name: shipping_line_uid
        data_type: string
        quote: true
      - name: shipping_line_price
        data_type: string
        quote: true
      - name: shipping_line_source
        data_type: string
        quote: true
      - name: shipping_line_tax_lines_price
        data_type: string
        quote: true
      - name: shipping_line_tax_lines_rate
        data_type: string
        quote: true
      - name: shipping_line_tax_lines_title
        data_type: string
        quote: true
      - name: shipping_line_title
        data_type: string
        quote: true
      - name: tax_line_price
        data_type: string
        quote: true
      - name: tax_line_rate
        data_type: string
        quote: true
      - name: tax_line_title
        data_type: string
        quote: true
      - name: taxes_included
        data_type: boolean
        quote: true
      - name: test
        data_type: boolean
        quote: true
